spring:
  jpa:
    # JPA Settings
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
    defer-datasource-initialization: true

  # 테스트 db 이름 설정
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  # H2 활성화
  h2:
    console:
      enabled: true

  #OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 880585075893-ruft3dmlvnjhatmvc87cunuh2n6hqmrm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: pkgun0727@gmail.com
  secret_key: ssafy-9th-class8